### ISSUE TITLE
No Icons show on quest

### ISSUE THREAD

**Issue by JarJarBlinkz** [barnabwhy/PicoZen#1]
does this have support for quest or is it specifically for the pico ?

only asking as installed games on the quest do not show or am i missing something...

**Comment by barnabwhy** [comment]
This is just for pico, although it should in theory show installed games on the quest as it simply uses `PackageManager.getInstalledApplications()` to fetch the app list

**Comment by JarJarBlinkz** [comment]
Thanks for the response.
But yeah the icons dont show in quest at all for any installed games only for system settings and other system stuff

**Comment by barnabwhy** [comment]
@Johnr79 would it be possible to send a screenshot of how the app looks on quest? I can't test on the device but i might be able to at least try and fix it

**Comment by JarJarBlinkz** [comment]
No problem I wil post one when i get online after work.

You do not need to try and fix it you dont want the hassle there are others
out there.

just liked the thought of the ftp feature

**Comment by JarJarBlinkz** [comment]
These are the only files that show and the headset has 11 installed games this is only a headset for the PTC so the only games are 3rd party games that only show in the unknown sources none are purchased from the meta store.
tryed getting a free game from the store which also does not show in the launcher.


![com oculus shellenv-20230517-143408](https://github.com/barnabwhy/PicoZen/assets/104454560/2255e296-2e21-42fb-b997-912e6a7342dc)

**Comment by barnabwhy** [comment]
could be some incompatibility due to quest 2 being on android 12L and pico being on android 10, i'll look into it though. unfortunately cause i can't test on a quest (i do not own one and am not willing to spend that kind of money to basically get a paperweight) i'll just try and wing it based on how basti does it in dreamgrid

**Comment by JarJarBlinkz** [comment]
No problem i am happy to keep testing it for you if you change anything

**Comment by barnabwhy** [comment]
@Johnr79 could you possibly test the build from the latest commit? it hopefully will fix the lack of apps showing on the quest

https://github.com/barnabwhy/PicoZen/suites/12989586524/artifacts/702970760

**Comment by Johnr79** [comment]
Will do soon as i am home from work

**Comment by Johnr79** [comment]
@barnabwhy so i just got the latest version but still the same not showing any apps but it also saying the last update was 3 days ago

**Comment by barnabwhy** [comment]
that's the one i linked above right and not release 0.3.0, right?

**Comment by JarJarBlinkz** [comment]
> @barnabwhy so i just got the latest version and yes that shows everything installed but now the drop down option for favourites/hidden and the drop down to organize by name etc no longer function

**Comment by barnabwhy** [comment]
Huh, good that apps work but strange that the dropdowns are broken. I can't really debug the dropdowns unfortunately cause they still work on PICO.

**Comment by Johnr79** [comment]
its all good thanks for trying though i appreciate it

**Comment by JarJarBlinkz** [comment]
@barnabwhy so after i have charged it and turned it back on the dropdowns are working fine
