### ISSUE TITLE
Library icon experimental func don't work correctly in 0.6.1

### ISSUE THREAD

**Issue by ZetaXis** [barnabwhy/PicoZen#11]
That's not problem in translation, because my fork version works fine (https://github.com/ZetaXis/PicoZen/releases)

How to try: 

1) Install PicoZen
2) Run PicoZen
3) Toggle Library experimental func
4) Close PicoZen (by B button)
5) Open PicoZen with Library icon
4) Trying run another app without closing PicoZen 
5) Try to open again PicoZen with Library icon

**Comment by reif22** [comment]
The same here, the last version that works for me is 0.5.1. When I activate it, I close PicoZen and after I use the Library Icon, the program closes itself and I cant open either libraries.

**Comment by KevORulz** [comment]
> The same here, the last version that works for me is 0.5.1. When I activate it, I close PicoZen and after I use the Library Icon, the program closes itself and I cant open either libraries.

Same here, partners. I had to downgrade to the aforementioned version in order to have the library shortcut working again. In newer versions it would only work the first time you boot into the system. After that, neither of the libraries would open, forcing me to reboot the headset.

**Comment by barnabwhy** [comment]
As of [v0.7.0](https://github.com/barnabwhy/PicoZen/releases/tag/0.7.0) I have reverted the behaviour to how it was in 0.5.1
