### ISSUE TITLE
Open launcher with explore app on quest.

### ISSUE THREAD

**Issue by Flumpmeister** [barnabwhy/PicoZen#2]
Loving this launcher since you updated it for the quest. 

The only thing that is stopping me switching to it full time is that is has to be launched manually every time you want to use it. Is there any chance you can add the option to launch it off the explore app similar to what you have with the pico option. PiLauncher Next already has this option if you needed reference.

The only other option I would like to see in the future is the ability to set how wide it opens. At the moment it opens wide enough to display 2 apps per row but would like to be able to open it wider to show 3 or 4 per row.

Great work tho and thanks for fixing it on quest.

**Comment by Flumpmeister** [comment]
I already changed this my end and compiled it and its working great. I still think this would be a good option to add tho. 

Maybe you could detect what device it is first and change the option based on that.

com.pvr.appmanager is what you are calling on pico and com.oculus.explore is the explore app on quest.

If you ever need any testing done on quest I am more than happy to help out. Thanks again.

**Comment by barnabwhy** [comment]
just added opening with explore in the most recent commit
