### ISSUE TITLE
Add an ability to sort apps into categories/tabs

### ISSUE THREAD

**Issue by cerega000** [barnabwhy/PicoZen#8]
It's pretty hard to navigate the launcher if you have lots of apps and games installed. I think it would be great to have an option to place apps into different categories.
If you dislike the idea of tabs (like in PiLauncher) maybe have some tags like games/apps/etc that you can manually apply to apps and then filter them like you already can with favorites.

Otherwise, really like the launcher. Really feels like it's a stock app.

**Comment by barnabwhy** [comment]
This feature is not planned since PiLauncher already implements it well. I'd suggest [PiLauncherNext](https://github.com/Veticia/PiLauncherNext) as it provides this functionality and works well (and the dev is cool)
